def mostrar_menu_empleados():
    print("\n" + "="*30)
    print("     GESTIÓN DE EMPLEADOS")
    print("="*30)
    print("1. Listar Empleados")
    print("2. Registrar Nuevo Empleado")
    print("3. Editar Cargo/Nombre")
    print("4. Eliminar Empleado")
    print("5. Volver al Menú Principal")
    print("="*30)